### ISSUE TITLE
一个训练的问题

### ISSUE THREAD

**Issue by afterimagex** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#10]
我想请教一下，如果我想要训练2k的图片，但是目标只有15x15pix 大小，如何调整训练参数呢？
我尝试用v2去训练，将bbox_small_list改为[7, 12, 17]，larget_list为[12, 17, 22]，修改feature_map_size_list为计算得到的size；
训练得到的模型什么都检测不出来？是哪里存在问题吗？

**Comment by afterimagex** [comment]
我有一个疑惑，是不是可以在320的小图上面训练，在2k的图像上测试？

**Comment by YonghaoHe** [comment]
@afterimagex

**Comment by YonghaoHe** [comment]
@afterimagex 
1,确认目标的尺度范围. 比如提到的目标是15x15, 那么它的可能的变化范围是多少,比如是10-30,那么就要根据这个范围去设计网络结构.
2,目标的长边和短边的比. **长边和需要多大的感受野有关系(需要感受野照顾到整个目标), 短边决定了感受野步长的大小设置(需要保证感受野中心命中目标).**
3,根据目标的属性,确定上下文信息是否有助于对目标进行分类. 这里会影响感受野的大小选择. 比如v1中的tiny部分,需要使用更多的上下文信息,故感受野需要更多一些.

有了以上信息,可以着手开始设计网络. 这里假定目标的范围是10-30pix,长边和短边的比约等于1,而且目标的分类基本不需要上下文信息. 
1,基本版: 网络开始连续两次下采样,此时感受野的步长是4, 第一个branch可以检测10-15, 感受野在40以上应该就可以了;第二个branch可以检测15-30, 感受野在70以上.
2,快速版:网络开始连续两次下采样,此时感受野的步长是4, 第一个branch可以检测10-15, 感受野在40以上应该就可以了;再进行一次下采样,此时的感受野步长是8,第二个branch可以检测15-30, 感受野在70以上.
以上只是一个建议,可以自行探索一下结构的设计.
训练阶段的网络输入大小是和你要检测目标物的最大尺寸有关系的, 比如这里你的目标最大30pix, 那么你的输入可以是128就足够了. 这样可以大大加速网络的训练. inference的阶段可以在任意尺寸的图像上进行,记住此时的网络能够检测的目标物尺寸范围是10-30pix, 和多大的图像尺寸没有关系.

**Comment by afterimagex** [comment]
非常感谢您能够在百忙之中抽出时间给出如此详尽的回答，非常感谢，我会再次尝试一下。

**Comment by 121649982** [comment]
> @afterimagex
> 1,确认目标的尺度范围. 比如提到的目标是15x15, 那么它的可能的变化范围是多少,比如是10-30,那么就要根据这个范围去设计网络结构.
> 2,目标的长边和短边的比. **长边和需要多大的感受野有关系(需要感受野照顾到整个目标), 短边决定了感受野步长的大小设置(需要保证感受野中心命中目标).**
> 3,根据目标的属性,确定上下文信息是否有助于对目标进行分类. 这里会影响感受野的大小选择. 比如v1中的tiny部分,需要使用更多的上下文信息,故感受野需要更多一些.
> 
> 有了以上信息,可以着手开始设计网络. 这里假定目标的范围是10-30pix,长边和短边的比约等于1,而且目标的分类基本不需要上下文信息.
> 1,基本版: 网络开始连续两次下采样,此时感受野的步长是4, 第一个branch可以检测10-15, 感受野在40以上应该就可以了;第二个branch可以检测15-30, 感受野在70以上.
> 2,快速版:网络开始连续两次下采样,此时感受野的步长是4, 第一个branch可以检测10-15, 感受野在40以上应该就可以了;再进行一次下采样,此时的感受野步长是8,第二个branch可以检测15-30, 感受野在70以上.
> 以上只是一个建议,可以自行探索一下结构的设计.
> 训练阶段的网络输入大小是和你要检测目标物的最大尺寸有关系的, 比如这里你的目标最大30pix, 那么你的输入可以是128就足够了. 这样可以大大加速网络的训练. inference的阶段可以在任意尺寸的图像上进行,记住此时的网络能够检测的目标物尺寸范围是10-30pix, 和多大的图像尺寸没有关系.

作者你好！请问一下：感受野在实际中是不是指：bbox_small_list和bbox_larget_list为里设计的尺寸？

**Comment by YonghaoHe** [comment]
@121649982 bbox_small_list和bbox_larget_list表示要检测的实际尺度范围。感受野需要自己通过网络结构去计算。

**Comment by 121649982** [comment]
@YonghaoHe ,好的，感谢
