### ISSUE TITLE
Four point detection

### ISSUE THREAD

**Issue by RamatovInomjon** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#101]
Hi @YonghaoHe 
Is it possible train four point detection model using this method?

**Comment by YonghaoHe** [comment]
@RamatovInomjon What is  four point detection, can you explain more ?

**Comment by RamatovInomjon** [comment]
I mean, all points of bbox. x1,y1, x2,y2,x3,y3,x4,y4 . I would get more accurate bbox. Usully we train using xmin,yminxmax,ymax

**Comment by YonghaoHe** [comment]
@RamatovInomjon why not try IOU loss？I don't think regressing four points can get more accurate bbox.

**Comment by RamatovInomjon** [comment]
Yes, you are right! Thanks for your response!
