### ISSUE TITLE
face detection model failed in the CPU environment

### ISSUE THREAD

**Issue by tairenchen** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#105]
Thank you for your good work with face detection.

It is working well in the GPU environment but failed in the CPU case.

System: Ubuntu 18.04.5 LTS"

Mxnet:  mxnet-mkl==1.6.0

Error information: A lot of bounding boxes are detected on the test image

My changes: In the folder: "LFFD-A-Light-and-Fast-Face-Detector-for-Edge-Devices/face_detection/accuracy_evaluation", I changed the  "ctx=mxnet.gpu(0)"  to "ctx=mxnet.cpu(0)" in the file: "predict.py"

See attached the image for more information
![test_result](https://user-images.githubusercontent.com/34171386/107816480-b0aac380-6d29-11eb-9668-08bc3d464de4.jpg)

**Comment by NgoJunHaoJason** [comment]
@tairenchen does it work if you use another version of mxnet, such as `mxnet-cu100mkl==1.5.1`?

**Comment by tairenchen** [comment]
Hi @NgoJunHaoJason 
      
Thank you for your reply.

I used the CPU version, so the version "mxnet-cu100mkl==1.5.1" you mentioned does not work. Because your version works for GPU environment, i.e.: CUDA available.

But I did give it a try, it gives me the error information as below:

![image](https://user-images.githubusercontent.com/34171386/107998177-63cd2400-6f99-11eb-8bce-2703894d98da.png)

**Comment by tairenchen** [comment]
Okay, the problem is solve when I install

Mxnet: mxnet-mkl==**1.5.0**

Thank you
