### ISSUE TITLE
Pedestrian Detection

### ISSUE THREAD

**Issue by gwestner94** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#11]
Hi @YonghaoHe,

Thank you for sharing your code,
do you make any specific changes in the trainingsframework when training for vehicle/ pedestrian detection compared to face detection? 
I am unsure on how much different object aspect ratios affect the system, as you mention in you paper that in the case of face detection we expect a near 1:1 aspect ratio. How do you modify your system to adjust for different aspect ratios?

Thx

**Comment by YonghaoHe** [comment]
@gwestner94
In short words, the longer side affects the selection of RF size (the RF needs to cover the object), the shorter side determine the RF stride (make sure the object will be hit by at least one RF center).
In pedestrian detection, the aspect ratio may become larger, like 1:3 or 1:5. Besides, pedestrians are always occluded, this means we have to detect full body and half body. To make it right, larger context information is necessary. So, we need different strategy to match RF size and object scale. 
We will release our model recently. By the way, how to match RF size and object scale is an open problem.

**Comment by YonghaoHe** [comment]
@gwestner94 We have released our first try of pedestrian detection on Caltech. You can check it. Hope it will help you.
