### ISSUE TITLE
How about multi-class detection?

### ISSUE THREAD

**Issue by leogogogo** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#15]
Hi @YonghaoHe,

Very nice work and thank you for sharing your code.
Do you think this framework could be extended to general multi-class detection case?

**Comment by YonghaoHe** [comment]
@leogogogo 
Indeed, we plan to extend one class detection to multi-class detection in the future. But in recent several months, we are working on the next generation of one class detection, making it more robust and faster.
The simplest way to try multi-class detection is to apply the idea of RF is the Natural Anchor to a SOTA multi-class detection method. Further discussion is welcome.

**Comment by smilence86** [comment]
I run face detect in realtime on raspberry pi 4b, inference time about 1.8s per frame. load average is around 4, 4 cores of cpu are almost 100% usage.

**Comment by YonghaoHe** [comment]
@smilence86 I don't really understand you. You means it is too slow? what kind of inference engine do you use?

**Comment by smilence86** [comment]
Yeah, as u said, The important thing is improve speed in recent servral months.
  
The accuracy is pretty good, I think it‘s could reduce accuracy for that when run on arm devices.
  
I tested v1 and v2, v1 about 2.6s, v2 about 1.8s

**Comment by YonghaoHe** [comment]
@smilence86 
On arm devices, the input resolution is usually small, like 120x160 or 240x320. Indeed, some optimizations can be added for faster inference.

**Comment by smilence86** [comment]
okay, sounds make sense, I reduce resolution to 240×320, v2 speed increase to ~500ms, the speed above are all tested with 640×480px.

**Comment by YonghaoHe** [comment]
@smilence86 which inference engine do you use ?

**Comment by smilence86** [comment]
@YonghaoHe I don't know where to change engine, It's all your code, I just add some code to use raspberry pi camera, you can see this [pull requests](https://github.com/YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices/pull/12)

**Comment by YonghaoHe** [comment]
@smilence86 you mean you use MXNet for inference on arm devices ? It is not a good choice. MNN, NCNN or Tegine are recommended. And use C++ instead of python

**Comment by smilence86** [comment]
@YonghaoHe got, thanks

**Comment by gwestner94** [comment]
@YonghaoHe have you tried porting the postprocessing code to C++? I see, that you have tables for a NCNN/MNN benchmark setup in the README.

**Comment by YonghaoHe** [comment]
@gwestner94 We use NCNN/MNN for latency evaluation, and this does not need postprocessing code. Currently, we do not have extra time for porting the postprocessing code to C++.

**Comment by YonghaoHe** [comment]
@smilence86 @leogogogo @gwestner94 @jeremycheong new [LFD](https://github.com/YonghaoHe/LFD-A-Light-and-Fast-Detector) is released, multi-class is supported!
