### ISSUE TITLE
hello,I get false true bbox during test phase, could you have some else details during traing phase？

### ISSUE THREAD

**Issue by heyang1021** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#16]
hello,I get false true bbox during test phase, could you have some else details during traing phase？

**Comment by YonghaoHe** [comment]
@heyang1021 false true? you mean false positive (wrong detection)?

**Comment by heyang1021** [comment]
I train 1,000,000 iterations, 
![2](https://user-images.githubusercontent.com/40254647/64577249-65f78000-d3ae-11e9-878a-a48f049b9d79.JPG)

**Comment by heyang1021** [comment]
@YonghaoHe  I train model to detect person's head,  run v1 on single GPU.

**Comment by YonghaoHe** [comment]
@heyang1021 What's your training data source ? 
In fact, we have trained a model of head detection for commercial deployment using our private dataset. It can perform head detection with very high accuracy. So I think something wrong in your training process.

**Comment by heyang1021** [comment]
@YonghaoHe  Training data is alse our private dataset. I just train 1,000,000 iterations, is that reason?

**Comment by YonghaoHe** [comment]
@heyang1021 Maybe 1,000,000 iterations is OK. But I see too many false positives and some missing cases in the image. How about the statistics of your private dataset?

**Comment by heyang1021** [comment]
@YonghaoHe Almost 15,000 images.

**Comment by YonghaoHe** [comment]
@heyang1021 if you can show me your training log?

**Comment by heyang1021** [comment]
@YonghaoHe 
[configuration_10_560_25L_8scales_v1_2019-09-03-16-04-20.log](https://github.com/YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices/files/3593504/configuration_10_560_25L_8scales_v1_2019-09-03-16-04-20.log)

**Comment by YonghaoHe** [comment]
@heyang1021 Hi friend. We have released the model for head detection, hope it will help you!

**Comment by heyang1021** [comment]
@YonghaoHe 
Thanks, I have trained it, and it looks very good.

**Comment by ghost** [comment]
> @YonghaoHe
> Thanks, I have trained it, and it looks very good.

I get the same problem that more than one bbox for an object; How could you solve this problem

**Comment by YonghaoHe** [comment]
@gray2bgr If you have trained your own model correctly, tuning score threshold and NMS threshold can help.
