### ISSUE TITLE
how to use FP16 in demo?

### ISSUE THREAD

**Issue by brucelee78** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#19]
Hi,thank you to open your code!
I use the demo in face_detection,on NVIDIA Jetson TX2, but the inference time is 70+ ms(640*480), I read your Readme.md file that inference time is  31.46ms(31.79FPS) on NVIDIA Jetson TX2，I think，I use the demo code probility works on FP32,
so I want to know that how to use FP16 in your demo on NVIDIA Jetson TX2!
thx

**Comment by YonghaoHe** [comment]
@brucelee78 
We work on FP32 too. The latency is evaluated using TensorRT. Please check code in inference_speed_evaluation.

**Comment by YonghaoHe** [comment]
@brucelee78 We have released [LFD](https://github.com/YonghaoHe/LFD-A-Light-and-Fast-Detector), have a try!
