### ISSUE TITLE
why param_receptive_field_center_start is [3, 3, 7, 7, ...] in model v1?

### ISSUE THREAD

**Issue by vealocia** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#20]
I am studying your code of LFFD and here comes some question. Why in the configuration of model v1, the param receptive field center start is written in list [3, 3, 7...]. just as the paper said, branch1 has a RF size of 55, so the center could not be at (3,3), can you give me an explanation?
Thanks a lot.

**Comment by vealocia** [comment]
<img width="608" alt="image" src="https://user-images.githubusercontent.com/45201863/65373257-96dc8c80-dcad-11e9-9ebd-eb562e5b495c.png">

**Comment by YonghaoHe** [comment]
@vealocia In the paper, we assumed that the readers know how RF related parameters are calculated. Thus, we do not present formulations. Here, I give you an example of how RF center starts are obtained. The example is presented in 1-D case.
![RF center](https://user-images.githubusercontent.com/28685653/65382373-30e81780-dd36-11e9-9843-f4027fd2e552.jpg)
