### ISSUE TITLE
请问预测时候要用什么样的输入尺寸

### ISSUE THREAD

**Issue by ghost** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#24]
你好，在预测时候使用不同的resize_scale得到的结果很不一样。与测试后是否需要设置与训练时候相同的尺寸呢？怎么才能确保预测是resize方式与训练的时候相同。

**Comment by YonghaoHe** [comment]
@gray2bgr 推断阶段, 任何尺寸的输入都是支持的, 不需要和训练阶段的尺寸一致.

**Comment by 394781865** [comment]
我用你的模型和代码在widerface数据集（val）上测试（原图输入），测试结果与你的结果有较大差距。这是什么原因？
