### ISSUE TITLE
question about train my dataset？

### ISSUE THREAD

**Issue by leemengxing** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#25]
Thank you for your work. I would like to ask if you train your own data set. Can we count the face size in our data set and delete the layers that do not exist in our data set? For example, my data set has only 320 * 240 image sizes and certainly no loss branch 8.

**Comment by YonghaoHe** [comment]
@leemengxing Of cause you can adjust the network to fit your case, if you are familiar with the method. In your case, 320*240 does not need large scales.
