### ISSUE TITLE
Stats on LFFD Face detection : GPU

### ISSUE THREAD

**Issue by dexception** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#26]
It is consuming about 1504 MB Gpu memory.
The MNN version is faster.
You should remove fast and lightweight from the title of this repo.

![image](https://user-images.githubusercontent.com/31848222/65831073-16341680-e2d3-11e9-81b6-c6475f8d21e5.png)

**Comment by eeric** [comment]
its speed was very slowly.
