### ISSUE TITLE
something about label own dataset

### ISSUE THREAD

**Issue by zzy0724** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#30]
Have you ever used labelimg to mark data? if you do this,can you share code about conveting file of xml to my train_llist.txt?
thank you !

**Comment by YonghaoHe** [comment]
@zzy0724  Sorry, we do not use labelimg. I think it is easy to convert to our format from any other formats. Please carefully read the code in data_provider_farm.
