### ISSUE TITLE
希望PyTorch version早点放出来,谢谢!

### ISSUE THREAD

**Issue by chinayb** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#31]

**Comment by YonghaoHe** [comment]
@chinayb 目前正在准备中,稍安勿躁.

**Comment by becauseofAI** [comment]
@chinayb 
The PyTorch preview version is released in [lffd branch](https://github.com/becauseofAI/refinanet/tree/lffd) of RefinaNet. Now you can try to train v2 version of the face task as same as the original mxnet version using this [script](https://github.com/becauseofAI/refinanet/blob/lffd/face_detection/config_farm/configuration_10_320_20L_5scales_v2.py).

**Comment by chinayb** [comment]
@YonghaoHe @chinayb 这么快就出来了，辛苦了，非常感谢！

**Comment by YonghaoHe** [comment]
@chinayb @jeremycheong @vicwer We have released [LFD](https://github.com/YonghaoHe/LFD-A-Light-and-Fast-Detector), have a try!
