### ISSUE TITLE
face_detection，运行inference_speed_evaluation/inference_speed_eval.py报错

### ISSUE THREAD

**Issue by lemonyhw** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#33]
INFO:root:Convert mxnet symbol to onnx...
INFO:root:Input shape of the model [(1, 3, 480, 640)] 
INFO:root:Exported ONNX file temp.onnx saved to disk
INFO:root:Parsing onnx for trt network...
ERROR:root:Errors occur while parsing the onnx file!
ERROR:root:Error 0: Assertion failed: tensor->getDimensions().nbDims == combined->getDimensions().nbDims

**Comment by YonghaoHe** [comment]
@lemonyhw 应该是TensorRT的版本问题,不支持解析你生成的ONNX版本的

**Comment by scutzhe** [comment]
请问作者使用的是哪个版本的tensorrt

**Comment by lemonyhw** [comment]
tensorrt5.0.2.6
