### ISSUE TITLE
Can I test the network through the cpu version of mxnet?

### ISSUE THREAD

**Issue by helloWorldFsz** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#35]
Can I test the network through the cpu version of mxnet?

**Comment by YonghaoHe** [comment]
@helloWorldFsz of course you can. MXNet+MKLDNN will be OK.

**Comment by eeric** [comment]
convert  ctx=mxnet.gpu(0)  to ctx=mxnet.cpu(0) in accuracy_evaluation/predict.py
