### ISSUE TITLE
it was general effect to trained model of pedestrian detection 

### ISSUE THREAD

**Issue by eeric** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#36]
it was big difference between trained model with your results.

**Comment by YonghaoHe** [comment]
@eeric I do not really understand what you mean

**Comment by eeric** [comment]
使用mxnet提供的行人检测模型测试效果没有你主页贴出的行人检测效果好。是不是你release的预训练模型效果一般的缘故。

**Comment by YonghaoHe** [comment]
@eeric 我们当时在Caltech上面训练的时候,训练数据的处理可能不是非常好,训练的时候比较随意,只是想出一个效果给大家一个示范. 我们release的就是能跑出repo贴出来的效果图的模型. model的效果并不是特别好,存在一定量的漏检和误检. Caltech这个数据库本身噪声挺大,建议用一些比较新的数据库,比如EuroCity Persons.

**Comment by eeric** [comment]
oh,明白，谢谢！
