### ISSUE TITLE
Table 2. Detailed information about the proposed network

### ISSUE THREAD

**Issue by sc199505** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#4]
您好，方便告诉我下Table2里的Ratio of RF and avg. face scale是怎么计算出来的么

**Comment by YonghaoHe** [comment]
@sc199505 
RF / ( (upper_bound+lower_bound)/2 )
for example: RF:55, scale [10, 15] -> ratio = 55 / ( (10+15)/2 ) = 4.4

**Comment by sc199505** [comment]
您好，谢谢您的回答，对于Table2 还有点不明白，论文里“For an instance, RFs of 100 pixels are able to predict faces between 20 pixels to 40 pixels.”是不是可以这样理解为对于实际感受野其范围是感受野的0.2倍到0.4倍之间，那么对于Table2里的Continuous face scale是不是可以由计算感受野的0.2~0.4计算得来，但是这样算下来:               
RF = 55    0.2 * RF = 11      0.4 * RF = 22 ;            11~22
RF = 71    0.2 * RF = 14.2   0.4 * RF = 28.4 ;        14.2~28.4
RF = 111  0.2 * RF = 22.2   0.4 * RF = 44.4;        22.2~44.4
RF = 143  0.2 * RF = 28.6   0.4 * RF = 57.2;        28.6~57.2
RF = 223  0.2 * RF = 44.6   0.4 * RF = 89.2;        44.6~89.2
RF = 383  0.2 * RF = 76.6   0.4 * RF = 153.2;      76.6~153.2
RF = 511  0.2 * RF = 102.2  0.4 * RF = 204.2;    102.2~204.2
RF = 639  0.2 * RF = 127.8  0.4 * RF = 255.6;     127.8~255.6
和Table2里的Continuous face scale明显不匹配，是不是我的理解有问题啊，望指教。

![image](https://user-images.githubusercontent.com/45219151/63321130-6756ff00-c352-11e9-9396-2d01f6021e42.png)

**Comment by YonghaoHe** [comment]
@sc199505 
具体来说,这里并没有一个定量的具体对应关系.
文中有相关的解释,这个设置(不同感受野针对不同尺度范围)会和具体的任务挂钩.
文中的backbone版本就如Table 2所示. repo中我们提供了v2的版本, 这个版本稍微简化了设计, 详情请参考/face_detection/symbol_farm/symbol_structures.xlsx.
文章的核心就是在讨论感受野应该如何去配合待检尺寸范围, 从而设计出更简洁的backbone.

**Comment by sc199505** [comment]
好的，谢谢您的回答。
