### ISSUE TITLE
关于backbone修改

### ISSUE THREAD

**Issue by 791136190** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#41]
你好，首先感谢你的开源。我们在你提供的backbone上进行了修改，把所有的卷积都修改为k=3，pad=1.这样的话，在计算感受野中心的时候，全部都是0.5了，取整为0的话，是否可行。还是说backbone设计的时候应该让感受野中心分布不同

**Comment by YonghaoHe** [comment]
完全可行,感受野的中心的起始位置在哪里都可以.

**Comment by 791136190** [comment]
感谢回复，如果增加pad参数，只用修改感受野中心和featuremap的大小就好了哈，其它的信息不需要修改？

**Comment by YonghaoHe** [comment]
对,输入尺寸变了,那么featuremap大小要变化,感受野中心只和网络结构本身有关系,和输入没关系.

**Comment by 791136190** [comment]
thks
