### ISSUE TITLE
Facial landmarks

### ISSUE THREAD

**Issue by thibault20cent** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#45]
Hi,
I'm very interested with your work in face detection, it's really good. I would like to add a feature to the lffd network to predict both bboxes and facial landmarks. I'm taking any hints on how you would proceed/if it's something possible (data is not a problem). For now my idea is to add a facial landmark loss (regression) in each loss branch and finetune the model.

**Comment by YonghaoHe** [comment]
yes, you can just add 4 featuremaps for landmark regression.
