### ISSUE TITLE
wrong detection result about pedestrian_detection

### ISSUE THREAD

**Issue by ailihong** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#50]
大佬您好：
　　首先，感谢开源．当我运行pedestrian_detection/accuracy_evaluation/predict.py,test_images文件夹下替换成其他640*480的行人图片时，检测框不在行人上，请问是什么原因。

希望大佬能不吝赐教，谢谢！

**Comment by YonghaoHe** [comment]
@ailihong 您好，首先我们是在caltech上随意训练的一个模型，所以这个模型跑别的图像，可能效果是有问题的。其次，如果是跑caltech的图像，你可以检查一下参数的设置是否正确。
