### ISSUE TITLE
执行python predict_tensorrt.py报错

### ISSUE THREAD

**Issue by 394781865** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#53]
INFO:root:Init engine from ONNX file.
INFO:root:Create TensorRT builder.
INFO:root:Create TensorRT network.
INFO:root:Create TensorRT ONNX parser.
ERROR:root:Errors occur while parsing the ONNX file!
Assertion failed: tensor->getDimensions().nbDims == combined->getDimensions().nbDims

这是哪里出了问题呢？

**Comment by 394781865** [comment]
上面的问题已经解决，但是执行predict_tensorrt.py遇到了新的问题。

File "predict_tensorrt.py", line 229, in do_inference
    x_lt_mat = RF_center_Xs_mat - bbox_map[0, :, :] * self.constant[i]
ValueError: operands could not be broadcast together with shapes (2,119) (119,159)

**Comment by 394781865** [comment]
没问题了，tensorrt的版本不对

**Comment by iqraJilani** [comment]
> 

Can you please let me know what was the version when you were getting this error and using which version resolved this issue?
