### ISSUE TITLE
训练曲线

### ISSUE THREAD

**Issue by kingofview** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#56]
楼主可以分享一下训练时候的loss曲线啊

**Comment by YonghaoHe** [comment]
@kingofview 这个曲线确实没有画过，但是趋势是从最深的branch开始下降，第一个branch最后下降，而且第一个开始下降的时间可能会比较晚。

**Comment by kingofview** [comment]
> @kingofview 这个曲线确实没有画过，但是趋势是从最深的branch开始下降，第一个branch最后下降，而且第一个开始下降的时间可能会比较晚。

好的，谢谢

**Comment by suyue6** [comment]
> 楼主可以分享一下训练时候的loss曲线啊

你好，请问你画出来了吗？谢谢

**Comment by kingofview** [comment]
> > 楼主可以分享一下训练时候的loss曲线啊
> 
> 你好，请问你画出来了吗？谢谢

我后来没继续训练LFFD了
