### ISSUE TITLE
关于车牌检测的得分

### ISSUE THREAD

**Issue by vicwer** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#57]
你好，
        车牌检测出来需要去识别，只要一个字符在检测框外识别就会错误，所以请问一下车牌检测的AP值0.989在计算时IoU_threshold设置的是多少，这个得分是保证车牌所有字符都在检测框内的计算出来的吗？

**Comment by YonghaoHe** [comment]
@vicwer 这个IOU阈值应该是0.5.

**Comment by vicwer** [comment]
好的，多谢
