### ISSUE TITLE
thank you for sharing your code, it's a wonderful job. I'm not familiar with mxnet, so when will you release pytorch version?

### ISSUE THREAD

**Issue by westnight** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#6]

**Comment by becauseofAI** [comment]
@westnight 
Coding without stopping.  It may be released in Sep.

**Comment by YonghaoHe** [comment]
It is coming!

**Comment by hanjw123** [comment]
will you release a tensorflow version?

**Comment by YonghaoHe** [comment]
@hanjw123 
Currently, TensorFlow version is not scheduled. But any third-party re-implementation are welcome!

**Comment by lucasjinreal** [comment]
Where does pytorch version released at?

**Comment by becauseofAI** [comment]
> Where does pytorch version released at?

The official README will provide the url.

**Comment by becauseofAI** [comment]
@westnight @jinfagang @hanjw123 
The PyTorch preview version is released in [lffd branch](https://github.com/becauseofAI/refinanet/tree/lffd) of RefinaNet. Now you can try to train v2 version of the face task as same as the original mxnet version using this [script](https://github.com/becauseofAI/refinanet/blob/lffd/face_detection/config_farm/configuration_10_320_20L_5scales_v2.py).
