### ISSUE TITLE
Accuracy Problem

### ISSUE THREAD

**Issue by PhenomenalOnee** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#60]
I have trained your v2 model using your given data
but my accuracy is far more poor than you
i have done 200000 iterations 
can you share your training procedure

**Comment by YonghaoHe** [comment]
@PhenomenalOnee At least, you have to run more than 1000000 iterations with batchsize = 32

**Comment by PhenomenalOnee** [comment]
Thanks for the reply, i will train it till 1000000 iterations and come back with the results.
