### ISSUE TITLE
GOOD JOB

### ISSUE THREAD

**Issue by keetsky** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#7]
Hoping pytorch vision bo be released

**Comment by becauseofAI** [comment]
@keetsky 
Coding without stopping.

**Comment by YonghaoHe** [comment]
It is on the way！

**Comment by becauseofAI** [comment]
@keetsky 
The PyTorch preview version is released in [lffd branch](https://github.com/becauseofAI/refinanet/tree/lffd) of RefinaNet. Now you can try to train v2 version of the face task as same as the original mxnet version using this [script](https://github.com/becauseofAI/refinanet/blob/lffd/face_detection/config_farm/configuration_10_320_20L_5scales_v2.py).
