### ISSUE TITLE
onnx.onnx_cpp2py_export.checker.ValidationError: Node (slice_axis20) has input size 1 not in range [min=3, max=5].  ==> Context: Bad node spec: input: "softmax0" output: "slice_axis20" name: "slice_axis20" op_type: "Slice" attribute { name: "axes" ints: 1 type: INTS } attribute { name: "ends" ints: 1 type: INTS } attribute { name: "starts" ints: 0 type: INTS }

### ISSUE THREAD

**Issue by xjiao004** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#8]
Any one knows what's the problem here? Really appreciate it !

**Comment by YonghaoHe** [comment]
Using protobuf 2.6 may solve your problem!

**Comment by xjiao004** [comment]
> Using protobuf 2.6 may solve your problem!

Thanks, I used protobuf==2.6, but it still encounter this problem.

**Comment by xjiao004** [comment]
> Using protobuf 2.6 may solve your problem!

Could you please show your configuration of the project's environment ? Thanks a  lot !

**Comment by YonghaoHe** [comment]
@xjiao004 
please show me you mxnet version, onnx version

**Comment by dunglt2015** [comment]
Hi, @YonghaoHe. I have a same problem with @xjiao004 and my package version below
> mxnet 1.5.0
> onnx 1.5.0 

@xjiao004 Have you solve this problem? 
Thanks you!

**Comment by lucasjinreal** [comment]
```
mxnet-cu101                   1.5.1.post0            
onnx                          1.6.0                  
onnx-simplifier               0.1.8                  
onnxexplorer                  0.0.5                  
onnxruntime-gpu-tensorrt      0.5.0 
```

Got same error here

**Comment by PhenomenalOnee** [comment]
use version of onnx==1.1.1
