### ISSUE TITLE
 Detection is not performed when there are large faces in the photos.

### ISSUE THREAD

**Issue by CengizhanYurdakul** [YonghaoHe/A-Light-and-Fast-Face-Detector-for-Edge-Devices#88]
In Predictor class, I change the values ​​of bbox_large_list and bbox_small_list, but the face is not detected in photos with large faces.

face_predictor = predict.Predict(mxnet=mx,
                                symbol_file_path=symbol_file_path,
                                model_file_path=model_file_path,
                                ctx=ctx,
                                receptive_field_list=cfg.param_receptive_field_list,
                                receptive_field_stride=cfg.param_receptive_field_stride,
                                bbox_small_list=cfg.param_bbox_small_list,
                                bbox_large_list=[800 * 100, 1600 * 100, 3200 * 100, 6400 * 100, 12800 * 100], 
                                receptive_field_center_start=cfg.param_receptive_field_center_start,
                                num_output_scales=cfg.param_num_output_scales)

![deneme](https://user-images.githubusercontent.com/53911245/84324611-9eb4c780-ab81-11ea-9881-3cc6bd0e74be.jpg)

**Comment by YonghaoHe** [comment]
@CengizhanYurdakul you misunderstand the parameters. bbox_small_list and bbox_large_list should not be changed. If you want to detect large faces, you have to resize the image.
